name: Update Index

on:
  push:
    branches: [ main ]
    paths:
    - '**.tgz'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Git Checkout
      uses: actions/checkout@v7
    - name: Helm Installation
      uses: azure/setup-helm@v5
      with:
        version: latest
    - name: Update Index
      run: |
        helm repo index .
        git config --global user.email "dev@listshop.com"
        git config --global user.name "Listshop Bot"
        git add index.yaml
        git commit -m "Update chart index"
        git push
